### ISSUE TITLE
"apps aren't loaded yet" exception on clean install, using installation instruction from docs.

### ISSUE THREAD

**Issue by arzon94** [doconix/django-mako-plus#34]
Following the docs installation instructions exactly raises an "Apps aren't loaded yet" exception.  full error message: 
`(venv) macs-MBP:BYU webdev mac$ python3 -m django_mako_plus dmp startproject goldenspikes
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_mai
n
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/django_mako_plus/__main__.py", line 51, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/django_mako_plus/__main__.py", line 46, in main

    management.execute_from_command_line()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 280, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 254, in create_parser
    self.add_arguments(parser)
  File "/usr/local/lib/python3.6/site-packages/django_mako_plus/management/commands/dmp.py", line 56, in add_arguments
    for name in find_subcommands():
  File "/usr/local/lib/python3.6/site-packages/django_mako_plus/management/commands/dmp.py", line 80, in find_subcommands
    dmp = apps.get_app_config('django_mako_plus')
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 145, in get_app_config
    self.check_apps_ready()
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 127, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.`

Is this an issue with the initial dmp template? you can install without dmp in the startproject command, but then cannot use dmp in startapp command

This was an issue on macOS and ubuntu

**Comment by brandenclark** [comment]
I had the same issue as well. Stack trace was a perfect match to Andy's, except my project name wasn't as cool as 'goldenspikes'. Even did a fresh install of python and my OS to no avail because I believed DMP to be infallible.

**Comment by arzon94** [comment]
Running the commands from a previous version of the docs works, even with the new version of dmp.  here they are in case someone needs them
`python3 -m django startproject --template=http://cdn.rawgit.com/doconix/django-mako-plus/master/project_template.zip mysite
`
`python3 manage.py startapp --template=http://cdn.rawgit.com/doconix/django-mako-plus/master/app_template.zip --extension=py,htm,html homepage`

**Comment by doconix** [comment]
Thanks for the report.  I'm working on it this morning and will have a fix posted.

**Comment by doconix** [comment]
This is fixed in 5.5.3.  Thanks for the error report!
